spring:
  application:
    name: VigieCam


    spring:
      datasource:
        url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?user=postgres.luwbjhzobklcbbheunmm&password=Sidolin%40199
        username: postgres.luwbjhzobklcbbheunmm
        password: ${DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            format_sql: true