spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5